defaults:
  - override hydra/job_logging: custom
  - _self_

wandb: False
seed: 1234
nf_pretrained_path: exps/neural_field/nf_qm9
dirname: ${nf_pretrained_path}/eval
eval_metric: sampling  # miou | sampling
save_grids_png: False
n_samples: 1000

# overwrite
split: train
debug: True
dset:
  data_aug: True
  batch_size: 1000
wjs:
  batch_size_render: 2000

# set the running dir
hydra:
  run:
    dir: ./${dirname}
  job:
    config:
      override_dirname:
        kv_sep: ""
        item_sep: "_"
        exclude_keys: ["exp_dir"]
